
  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "NEWTANVI"."VIEW1" ("COLUMN1", "COLUMN2", "COLUMN3") AS 
  SELECT "COLUMN1","COLUMN2","COLUMN3"
    
FROM EMP;


  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "NEWTANVI"."VIEW2" ("COLUMN1", "COLUMN2", "COLUMN3") AS 
  SELECT "COLUMN1","COLUMN2","COLUMN3"
    
FROM COMP;

